### ISSUE TITLE
do_umap() Error in `step_umap()`

### ISSUE THREAD

**Issue by eemiljohansson** [HDA1472/DA_RPackage#41]
While following the vignette with the example data executing the function do_umap() I got the following error from this execution: 

```
do_umap(imputed_data, 
        clean_metadata,
        color = "Disease",
        palette = NULL,
        impute = FALSE)
```

```
Error in `step_umap()`:
Caused by error in `irlba::irlba()`:
! function 'as_cholmod_sparse' not provided by package 'Matrix'
Backtrace:
  1. HDAnalyzeR::do_umap(...)
 12. uwot::umap(...)
 13. uwot:::uwot(...)
 14. uwot:::spectral_init(V, ndim = n_components, verbose = verbose)
 15. uwot:::irlba_tsvd_normalized_laplacian_init(A, ndim, verbose = FALSE)
 16. uwot:::irlba_spectral_tsvd(L, ndim + 1)
 19. irlba::irlba(L, nv = n, nu = 0, maxit = iters)
```
Here's also the full traceback:
![image](https://github.com/user-attachments/assets/1abe7b76-aecd-4d18-9a4f-132f88496e44)
![image](https://github.com/user-attachments/assets/ae912040-e29f-4a86-a877-751b8b0cc226)

Here's my session_info()
![image](https://github.com/user-attachments/assets/e7d37bf7-8fba-499e-978d-c96f8479459f)
![image](https://github.com/user-attachments/assets/edba12a4-6660-42e3-b64b-6696b11316e3)

**Solved!**
I've solved this issue by making sure that I have loaded the `umap` package (v.0.2.10.0).

Should the `umap` package be an requirement or can it be solved in another way, or how can this error be avoided for other users?

**Comment by kantonopoulos** [comment]
It is fixed now. `umap` package is forced to load when calling the function and is added in HDAnalyzeR's dependencies.
