### ISSUE TITLE
Error: 'grid_space_filling' is not an exported object from 'namespace:dials'

### ISSUE THREAD

**Issue by jjkenrick** [HDA1472/DA_RPackage#47]
Ran do_rf_multi() function and received this error. Updated R version to 4.4.1 tidymodels to 1.2.0 and dials to 1.3.0 and it fixed the issue.

` HDAnalyzeR::do_rf_multi(auto_data,auto_meta,wide = FALSE,palette = 'pal_auto',exclude_cols = c('Sex','Age'))
Joining with `by = join_by(DAid)`Sets are ready. Multiclassification model fitting is starting...
Error: 'grid_space_filling' is not an exported object from 'namespace:dials'`

**Comment by kantonopoulos** [comment]
Hey! `grid_space_filling` is a new function in `dials` package (v1.3.0), so in order to make it work update `dials` and `tidymodels` in latest CRAN version.
